// Generated by scripts/import-cc0-backgrounds.mjs. Do not edit by hand.
import type { Photo } from "./photos";

export const additionalPhotos: Photo[] = [
  {
    "id": "cc0-01",
    "name": "11gemiler(VolkanOlmez)",
    "file": "backgrounds/cc0-01.webp",
    "thumbnail": "backgrounds/thumbs/cc0-01.webp",
    "author": "Volkan Olmez",
    "source": "https://commons.wikimedia.org/wiki/File%3A11gemiler(VolkanOlmez).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-02",
    "name": "120 E 8th St, Los Angeles, United States (Unsplash)",
    "file": "backgrounds/cc0-02.webp",
    "thumbnail": "backgrounds/thumbs/cc0-02.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A120_E_8th_St%2C_Los_Angeles%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-03",
    "name": "21 Poland St, London, United Kingdom (Unsplash)",
    "file": "backgrounds/cc0-03.webp",
    "thumbnail": "backgrounds/thumbs/cc0-03.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A21_Poland_St%2C_London%2C_United_Kingdom_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-04",
    "name": "153 W 27th St, New York, United States (Unsplash)",
    "file": "backgrounds/cc0-04.webp",
    "thumbnail": "backgrounds/thumbs/cc0-04.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A153_W_27th_St%2C_New_York%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-05",
    "name": "120 E 8th Street, Los Angeles, California (Unsplash)",
    "file": "backgrounds/cc0-05.webp",
    "thumbnail": "backgrounds/thumbs/cc0-05.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A120_E_8th_Street%2C_Los_Angeles%2C_California_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-06",
    "name": "1731 Berkeley Avenue, Los Angeles, California (Unsplash)",
    "file": "backgrounds/cc0-06.webp",
    "thumbnail": "backgrounds/thumbs/cc0-06.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A1731_Berkeley_Avenue%2C_Los_Angeles%2C_California_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-07",
    "name": "11 (Unsplash)",
    "file": "backgrounds/cc0-07.webp",
    "thumbnail": "backgrounds/thumbs/cc0-07.webp",
    "author": "Alvin Mahmudov alvinmahmudov",
    "source": "https://commons.wikimedia.org/wiki/File%3A11_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-08",
    "name": "17 (Unsplash)",
    "file": "backgrounds/cc0-08.webp",
    "thumbnail": "backgrounds/thumbs/cc0-08.webp",
    "author": "Alvin Mahmudov alvinmahmudov",
    "source": "https://commons.wikimedia.org/wiki/File%3A17_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-09",
    "name": "22, Bridal bouquet (Unsplash)",
    "file": "backgrounds/cc0-09.webp",
    "thumbnail": "backgrounds/thumbs/cc0-09.webp",
    "author": "Alvin Mahmudov alvinmahmudov",
    "source": "https://commons.wikimedia.org/wiki/File%3A22%2C_Bridal_bouquet_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-10",
    "name": "(NOT A) Drone view of golden gate bridge (Unsplash)",
    "file": "backgrounds/cc0-10.webp",
    "thumbnail": "backgrounds/thumbs/cc0-10.webp",
    "author": "Chris Leipelt cleipelt",
    "source": "https://commons.wikimedia.org/wiki/File%3A(NOT_A)_Drone_view_of_golden_gate_bridge_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-11",
    "name": "207 King St, London, Canada (Unsplash)",
    "file": "backgrounds/cc0-11.webp",
    "thumbnail": "backgrounds/thumbs/cc0-11.webp",
    "author": "Scott Webb scottwebb",
    "source": "https://commons.wikimedia.org/wiki/File%3A207_King_St%2C_London%2C_Canada_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-12",
    "name": "100DaysOfCode (Unsplash)",
    "file": "backgrounds/cc0-12.webp",
    "thumbnail": "backgrounds/thumbs/cc0-12.webp",
    "author": "Lewis Ngugi ngeshlew",
    "source": "https://commons.wikimedia.org/wiki/File%3A100DaysOfCode_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-13",
    "name": "102-stop elevator ride to heaven (Unsplash)",
    "file": "backgrounds/cc0-13.webp",
    "thumbnail": "backgrounds/thumbs/cc0-13.webp",
    "author": "Mark Asthoff qa9de",
    "source": "https://commons.wikimedia.org/wiki/File%3A102-stop_elevator_ride_to_heaven_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-14",
    "name": "10 Bands. 50 Bands. 100 Bands- (Unsplash)",
    "file": "backgrounds/cc0-14.webp",
    "thumbnail": "backgrounds/thumbs/cc0-14.webp",
    "author": "Khachik Simonian khachiksimonian",
    "source": "https://commons.wikimedia.org/wiki/File%3A10_Bands._50_Bands._100_Bands-_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-15",
    "name": "18 Broad St, Charleston, United States (Unsplash)",
    "file": "backgrounds/cc0-15.webp",
    "thumbnail": "backgrounds/thumbs/cc0-15.webp",
    "author": "Adam DeHaven adamdehaven",
    "source": "https://commons.wikimedia.org/wiki/File%3A18_Broad_St%2C_Charleston%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-16",
    "name": "11 Depot St, Concord, United States (Unsplash)",
    "file": "backgrounds/cc0-16.webp",
    "thumbnail": "backgrounds/thumbs/cc0-16.webp",
    "author": "Michael Browning michaelwb",
    "source": "https://commons.wikimedia.org/wiki/File%3A11_Depot_St%2C_Concord%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-17",
    "name": "1145 Market St, San Francisco, United States (Unsplash)",
    "file": "backgrounds/cc0-17.webp",
    "thumbnail": "backgrounds/thumbs/cc0-17.webp",
    "author": "Andrew Collins andrewcollins",
    "source": "https://commons.wikimedia.org/wiki/File%3A1145_Market_St%2C_San_Francisco%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-18",
    "name": "1611 Telegraph Ave, Oakland, United States (Unsplash)",
    "file": "backgrounds/cc0-18.webp",
    "thumbnail": "backgrounds/thumbs/cc0-18.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A1611_Telegraph_Ave%2C_Oakland%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-19",
    "name": "1421 S Old Baltimore Pike, Newark, United States (Unsplash)",
    "file": "backgrounds/cc0-19.webp",
    "thumbnail": "backgrounds/thumbs/cc0-19.webp",
    "author": "Mike Petrucci mikepetrucci",
    "source": "https://commons.wikimedia.org/wiki/File%3A1421_S_Old_Baltimore_Pike%2C_Newark%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-20",
    "name": "15A Hanover St interior (Unsplash)",
    "file": "backgrounds/cc0-20.webp",
    "thumbnail": "backgrounds/thumbs/cc0-20.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A15A_Hanover_St_interior_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-21",
    "name": "21 (Unsplash)",
    "file": "backgrounds/cc0-21.webp",
    "thumbnail": "backgrounds/thumbs/cc0-21.webp",
    "author": "Alvin Mahmudov alvinmahmudov",
    "source": "https://commons.wikimedia.org/wiki/File%3A21_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-22",
    "name": "\"Make art not war” mural (Unsplash pJu2NCjopwQ)",
    "file": "backgrounds/cc0-22.webp",
    "thumbnail": "backgrounds/thumbs/cc0-22.webp",
    "author": "Randy Tarampi randytarampi",
    "source": "https://commons.wikimedia.org/wiki/File%3A%22Make_art_not_war%E2%80%9D_mural_(Unsplash_pJu2NCjopwQ).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-23",
    "name": "\"Hello beautiful” sign on building (Unsplash)",
    "file": "backgrounds/cc0-23.webp",
    "thumbnail": "backgrounds/thumbs/cc0-23.webp",
    "author": "Ian Schneider goian",
    "source": "https://commons.wikimedia.org/wiki/File%3A%22Hello_beautiful%E2%80%9D_sign_on_building_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-24",
    "name": "10th Street Bridge, Pittsburgh, United States (Unsplash)",
    "file": "backgrounds/cc0-24.webp",
    "thumbnail": "backgrounds/thumbs/cc0-24.webp",
    "author": "Willie Fineberg willie_f",
    "source": "https://commons.wikimedia.org/wiki/File%3A10th_Street_Bridge%2C_Pittsburgh%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-25",
    "name": "2016 Mustang GT, San Francisco, United States (Unsplash)",
    "file": "backgrounds/cc0-25.webp",
    "thumbnail": "backgrounds/thumbs/cc0-25.webp",
    "author": "Joey Banks joeyabanks",
    "source": "https://commons.wikimedia.org/wiki/File%3A2016_Mustang_GT%2C_San_Francisco%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-26",
    "name": "10,000 Ft (Unsplash)",
    "file": "backgrounds/cc0-26.webp",
    "thumbnail": "backgrounds/thumbs/cc0-26.webp",
    "author": "Lisa Ung lisau04",
    "source": "https://commons.wikimedia.org/wiki/File%3A10%2C000_Ft_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-27",
    "name": "16825 Co Rd 162, Nathrop, United States (Unsplash)",
    "file": "backgrounds/cc0-27.webp",
    "thumbnail": "backgrounds/thumbs/cc0-27.webp",
    "author": "David Schertz dschertzphoto",
    "source": "https://commons.wikimedia.org/wiki/File%3A16825_Co_Rd_162%2C_Nathrop%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-28",
    "name": "11 Beacon St, Boston, United States (Unsplash)",
    "file": "backgrounds/cc0-28.webp",
    "thumbnail": "backgrounds/thumbs/cc0-28.webp",
    "author": "Matthew Landers mlanders87",
    "source": "https://commons.wikimedia.org/wiki/File%3A11_Beacon_St%2C_Boston%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-29",
    "name": "15th street stop (Unsplash)",
    "file": "backgrounds/cc0-29.webp",
    "thumbnail": "backgrounds/thumbs/cc0-29.webp",
    "author": "Joren Frielink jorenfrielink",
    "source": "https://commons.wikimedia.org/wiki/File%3A15th_street_stop_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-30",
    "name": "042217 (Unsplash)",
    "file": "backgrounds/cc0-30.webp",
    "thumbnail": "backgrounds/thumbs/cc0-30.webp",
    "author": "Omair Khan omairk",
    "source": "https://commons.wikimedia.org/wiki/File%3A042217_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-31",
    "name": "\"Together, we create!” on brick wall (Unsplash)",
    "file": "backgrounds/cc0-31.webp",
    "thumbnail": "backgrounds/thumbs/cc0-31.webp",
    "author": "\"My Life Through A Lens\" bamagal",
    "source": "https://commons.wikimedia.org/wiki/File%3A%22Together%2C_we_create!%E2%80%9D_on_brick_wall_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-32",
    "name": "2-42 Community Church, Brighton worship service (Unsplash)",
    "file": "backgrounds/cc0-32.webp",
    "thumbnail": "backgrounds/thumbs/cc0-32.webp",
    "author": "Bill Hamway billhamway",
    "source": "https://commons.wikimedia.org/wiki/File%3A2-42_Community_Church%2C_Brighton_worship_service_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-33",
    "name": "1235 Ala Kapuna St, Honolulu, United States (Unsplash)",
    "file": "backgrounds/cc0-33.webp",
    "thumbnail": "backgrounds/thumbs/cc0-33.webp",
    "author": "Coby Shimabukuro cobyshimabukuro",
    "source": "https://commons.wikimedia.org/wiki/File%3A1235_Ala_Kapuna_St%2C_Honolulu%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-34",
    "name": "1991 (Unsplash)",
    "file": "backgrounds/cc0-34.webp",
    "thumbnail": "backgrounds/thumbs/cc0-34.webp",
    "author": "Felix Russell-Saw frsphoto",
    "source": "https://commons.wikimedia.org/wiki/File%3A1991_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-35",
    "name": "\"My Life Through A Lens\" 2016-07-06 (Unsplash)",
    "file": "backgrounds/cc0-35.webp",
    "thumbnail": "backgrounds/thumbs/cc0-35.webp",
    "author": "\"My Life Through A Lens\" bamagal",
    "source": "https://commons.wikimedia.org/wiki/File%3A%22My_Life_Through_A_Lens%22_2016-07-06_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-36",
    "name": "\"wink” (Unsplash)",
    "file": "backgrounds/cc0-36.webp",
    "thumbnail": "backgrounds/thumbs/cc0-36.webp",
    "author": "marc liu notmarcliu",
    "source": "https://commons.wikimedia.org/wiki/File%3A%22wink%E2%80%9D_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-37",
    "name": "16004 Devonshire St, Los Angeles, United States (Unsplash)",
    "file": "backgrounds/cc0-37.webp",
    "thumbnail": "backgrounds/thumbs/cc0-37.webp",
    "author": "Hugo Alfredo Aguilar Jr onexmost",
    "source": "https://commons.wikimedia.org/wiki/File%3A16004_Devonshire_St%2C_Los_Angeles%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-38",
    "name": "'Friendship alleys' in Yazd, Iran. (Unsplash)",
    "file": "backgrounds/cc0-38.webp",
    "thumbnail": "backgrounds/thumbs/cc0-38.webp",
    "author": "Sander van Dijk sandervd",
    "source": "https://commons.wikimedia.org/wiki/File%3A'Friendship_alleys'_in_Yazd%2C_Iran._(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-39",
    "name": "\"Hand-made art and design” sign (Unsplash)",
    "file": "backgrounds/cc0-39.webp",
    "thumbnail": "backgrounds/thumbs/cc0-39.webp",
    "author": "Peter Miranda petermiranda",
    "source": "https://commons.wikimedia.org/wiki/File%3A%22Hand-made_art_and_design%E2%80%9D_sign_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-40",
    "name": "223 edit (1 of 1) (Unsplash)",
    "file": "backgrounds/cc0-40.webp",
    "thumbnail": "backgrounds/thumbs/cc0-40.webp",
    "author": "Kim Cafferky cafferkyphotography",
    "source": "https://commons.wikimedia.org/wiki/File%3A223_edit_(1_of_1)_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-41",
    "name": "1022 SW Stark St, Portland, United States (Unsplash)",
    "file": "backgrounds/cc0-41.webp",
    "thumbnail": "backgrounds/thumbs/cc0-41.webp",
    "author": "Bill Anastas banastas",
    "source": "https://commons.wikimedia.org/wiki/File%3A1022_SW_Stark_St%2C_Portland%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-42",
    "name": "240sx (Unsplash)",
    "file": "backgrounds/cc0-42.webp",
    "thumbnail": "backgrounds/thumbs/cc0-42.webp",
    "author": "Ivan Sean ivsean",
    "source": "https://commons.wikimedia.org/wiki/File%3A240sx_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-43",
    "name": "2gaugeBridge(buffer-view)",
    "file": "backgrounds/cc0-43.webp",
    "thumbnail": "backgrounds/thumbs/cc0-43.webp",
    "author": "Tiago Gerken",
    "source": "https://commons.wikimedia.org/wiki/File%3A2gaugeBridge(buffer-view).JPG",
    "color": "#183440"
  },
  {
    "id": "cc0-44",
    "name": "2piers2lighthouses",
    "file": "backgrounds/cc0-44.webp",
    "thumbnail": "backgrounds/thumbs/cc0-44.webp",
    "author": "Yinan Chen",
    "source": "https://commons.wikimedia.org/wiki/File%3A2piers2lighthouses.jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-45",
    "name": "2sitting@seewall(byElisabettaFoco)",
    "file": "backgrounds/cc0-45.webp",
    "thumbnail": "backgrounds/thumbs/cc0-45.webp",
    "author": "Elisabetta Foco",
    "source": "https://commons.wikimedia.org/wiki/File%3A2sitting%40seewall(byElisabettaFoco).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-46",
    "name": "4WD@dunes(byDEM)",
    "file": "backgrounds/cc0-46.webp",
    "thumbnail": "backgrounds/thumbs/cc0-46.webp",
    "author": "Dyaa Eldin Moustafa",
    "source": "https://commons.wikimedia.org/wiki/File%3A4WD%40dunes(byDEM).JPG",
    "color": "#183440"
  },
  {
    "id": "cc0-47",
    "name": "3tankers@ThessalonikiPort",
    "file": "backgrounds/cc0-47.webp",
    "thumbnail": "backgrounds/thumbs/cc0-47.webp",
    "author": "John Maravelakis",
    "source": "https://commons.wikimedia.org/wiki/File%3A3tankers%40ThessalonikiPort.jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-48",
    "name": "2taxis@NYC",
    "file": "backgrounds/cc0-48.webp",
    "thumbnail": "backgrounds/thumbs/cc0-48.webp",
    "author": "Andrew Ruiz",
    "source": "https://commons.wikimedia.org/wiki/File%3A2taxis%40NYC.jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-49",
    "name": "2amarelos@SLuzia",
    "file": "backgrounds/cc0-49.webp",
    "thumbnail": "backgrounds/thumbs/cc0-49.webp",
    "author": "D. Gomes Ascensão http://www.por7o.com/ https://twitter.com/POR7O",
    "source": "https://commons.wikimedia.org/wiki/File%3A2amarelos%40SLuzia.JPG",
    "color": "#183440"
  },
  {
    "id": "cc0-50",
    "name": "54th Street, Newport Beach, United States (Unsplash)",
    "file": "backgrounds/cc0-50.webp",
    "thumbnail": "backgrounds/thumbs/cc0-50.webp",
    "author": "Austin Neill arstyy",
    "source": "https://commons.wikimedia.org/wiki/File%3A54th_Street%2C_Newport_Beach%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-51",
    "name": "32 (Unsplash)",
    "file": "backgrounds/cc0-51.webp",
    "thumbnail": "backgrounds/thumbs/cc0-51.webp",
    "author": "Alvin Mahmudov alvinmahmudov",
    "source": "https://commons.wikimedia.org/wiki/File%3A32_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-52",
    "name": "38 Rosebery Ave, London, United Kingdom (Unsplash)",
    "file": "backgrounds/cc0-52.webp",
    "thumbnail": "backgrounds/thumbs/cc0-52.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A38_Rosebery_Ave%2C_London%2C_United_Kingdom_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-53",
    "name": "26 Broadway, New York, United States (Unsplash)",
    "file": "backgrounds/cc0-53.webp",
    "thumbnail": "backgrounds/thumbs/cc0-53.webp",
    "author": "Breather breather",
    "source": "https://commons.wikimedia.org/wiki/File%3A26_Broadway%2C_New_York%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-54",
    "name": "2K Life (Unsplash)",
    "file": "backgrounds/cc0-54.webp",
    "thumbnail": "backgrounds/thumbs/cc0-54.webp",
    "author": "Rhett Noonan rhett_noonan",
    "source": "https://commons.wikimedia.org/wiki/File%3A2K_Life_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-55",
    "name": "36 (Unsplash)",
    "file": "backgrounds/cc0-55.webp",
    "thumbnail": "backgrounds/thumbs/cc0-55.webp",
    "author": "Alvin Mahmudov alvinmahmudov",
    "source": "https://commons.wikimedia.org/wiki/File%3A36_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-56",
    "name": "35 King Street, Bristol, United Kingdom (Unsplash)",
    "file": "backgrounds/cc0-56.webp",
    "thumbnail": "backgrounds/thumbs/cc0-56.webp",
    "author": "Green Chameleon craftedbygc",
    "source": "https://commons.wikimedia.org/wiki/File%3A35_King_Street%2C_Bristol%2C_United_Kingdom_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-57",
    "name": "40th Floor (Unsplash)",
    "file": "backgrounds/cc0-57.webp",
    "thumbnail": "backgrounds/thumbs/cc0-57.webp",
    "author": "Miguel Gonzalez magnusdiv",
    "source": "https://commons.wikimedia.org/wiki/File%3A40th_Floor_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-58",
    "name": "2775 Mesa Verde Dr E, Costa Mesa, United States (Unsplash)",
    "file": "backgrounds/cc0-58.webp",
    "thumbnail": "backgrounds/thumbs/cc0-58.webp",
    "author": "Albert Dera albertdera",
    "source": "https://commons.wikimedia.org/wiki/File%3A2775_Mesa_Verde_Dr_E%2C_Costa_Mesa%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-59",
    "name": "26 E Mallory Ave, Memphis, United States (Unsplash)",
    "file": "backgrounds/cc0-59.webp",
    "thumbnail": "backgrounds/thumbs/cc0-59.webp",
    "author": "Khara Woods kharaoke",
    "source": "https://commons.wikimedia.org/wiki/File%3A26_E_Mallory_Ave%2C_Memphis%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-60",
    "name": "543 E 5th St, New York, United States (Unsplash)",
    "file": "backgrounds/cc0-60.webp",
    "thumbnail": "backgrounds/thumbs/cc0-60.webp",
    "author": "Kevin Lee kevin_lee",
    "source": "https://commons.wikimedia.org/wiki/File%3A543_E_5th_St%2C_New_York%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-61",
    "name": "3rd birthday cake (Unsplash 10b8Lvvc-4g)",
    "file": "backgrounds/cc0-61.webp",
    "thumbnail": "backgrounds/thumbs/cc0-61.webp",
    "author": "Annie Spratt anniespratt",
    "source": "https://commons.wikimedia.org/wiki/File%3A3rd_birthday_cake_(Unsplash_10b8Lvvc-4g).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-62",
    "name": "3AM (Unsplash)",
    "file": "backgrounds/cc0-62.webp",
    "thumbnail": "backgrounds/thumbs/cc0-62.webp",
    "author": "Chris Benson maui354",
    "source": "https://commons.wikimedia.org/wiki/File%3A3AM_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-63",
    "name": "3 Sarny, Supraśl, Poland (Unsplash)",
    "file": "backgrounds/cc0-63.webp",
    "thumbnail": "backgrounds/thumbs/cc0-63.webp",
    "author": "Pawel Franke frankovsky",
    "source": "https://commons.wikimedia.org/wiki/File%3A3_Sarny%2C_Supra%C5%9Bl%2C_Poland_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-64",
    "name": "43 Essex Street, London WC2",
    "file": "backgrounds/cc0-64.webp",
    "thumbnail": "backgrounds/thumbs/cc0-64.webp",
    "author": "Samuel Zeller samuelzeller",
    "source": "https://commons.wikimedia.org/wiki/File%3A43_Essex_Street%2C_London_WC2.jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-65",
    "name": "360 Photo in Bookstore (Unsplash)",
    "file": "backgrounds/cc0-65.webp",
    "thumbnail": "backgrounds/thumbs/cc0-65.webp",
    "author": "Pj Accetturo pjaccetturo",
    "source": "https://commons.wikimedia.org/wiki/File%3A360_Photo_in_Bookstore_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-66",
    "name": "30 Hours (Unsplash)",
    "file": "backgrounds/cc0-66.webp",
    "thumbnail": "backgrounds/thumbs/cc0-66.webp",
    "author": "Byron Johnson byronism",
    "source": "https://commons.wikimedia.org/wiki/File%3A30_Hours_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-67",
    "name": "360 Chicago (Unsplash)",
    "file": "backgrounds/cc0-67.webp",
    "thumbnail": "backgrounds/thumbs/cc0-67.webp",
    "author": "Kevin Rajaram kevinrajaram",
    "source": "https://commons.wikimedia.org/wiki/File%3A360_Chicago_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-68",
    "name": "53rd St Sunrise (Unsplash)",
    "file": "backgrounds/cc0-68.webp",
    "thumbnail": "backgrounds/thumbs/cc0-68.webp",
    "author": "ben o'bro benobro",
    "source": "https://commons.wikimedia.org/wiki/File%3A53rd_St_Sunrise_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-69",
    "name": "30 St Mary Axe (The Gherkin), London, United Kingdom (Unsplash)",
    "file": "backgrounds/cc0-69.webp",
    "thumbnail": "backgrounds/thumbs/cc0-69.webp",
    "author": "Samuel Zeller samuelzeller",
    "source": "https://commons.wikimedia.org/wiki/File%3A30_St_Mary_Axe_(The_Gherkin)%2C_London%2C_United_Kingdom_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-70",
    "name": "280 SL Automatic car (Unsplash Xg8teremqDc)",
    "file": "backgrounds/cc0-70.webp",
    "thumbnail": "backgrounds/thumbs/cc0-70.webp",
    "author": "Clem Onojeghuo clemono2",
    "source": "https://commons.wikimedia.org/wiki/File%3A280_SL_Automatic_car_(Unsplash_Xg8teremqDc).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-71",
    "name": "4th of July Maine sunset (Unsplash)",
    "file": "backgrounds/cc0-71.webp",
    "thumbnail": "backgrounds/thumbs/cc0-71.webp",
    "author": "Justin Bisson Beck justinbissonbeck",
    "source": "https://commons.wikimedia.org/wiki/File%3A4th_of_July_Maine_sunset_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-72",
    "name": "50323, Urbandale, United States (Unsplash)",
    "file": "backgrounds/cc0-72.webp",
    "thumbnail": "backgrounds/thumbs/cc0-72.webp",
    "author": "Drew Hays drew_hays",
    "source": "https://commons.wikimedia.org/wiki/File%3A50323%2C_Urbandale%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-73",
    "name": "24 N 33rd St, Philadelphia, United States (Unsplash)",
    "file": "backgrounds/cc0-73.webp",
    "thumbnail": "backgrounds/thumbs/cc0-73.webp",
    "author": "Jerry Kiesewetter jerryinocmd",
    "source": "https://commons.wikimedia.org/wiki/File%3A24_N_33rd_St%2C_Philadelphia%2C_United_States_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-74",
    "name": "404 (Unsplash)",
    "file": "backgrounds/cc0-74.webp",
    "thumbnail": "backgrounds/thumbs/cc0-74.webp",
    "author": "Scott Webb scottwebb",
    "source": "https://commons.wikimedia.org/wiki/File%3A404_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-75",
    "name": "51 (Unsplash)",
    "file": "backgrounds/cc0-75.webp",
    "thumbnail": "backgrounds/thumbs/cc0-75.webp",
    "author": "Pipe A. pipeaguileram",
    "source": "https://commons.wikimedia.org/wiki/File%3A51_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-76",
    "name": "301+ Kim 2015 (Unsplash)",
    "file": "backgrounds/cc0-76.webp",
    "thumbnail": "backgrounds/thumbs/cc0-76.webp",
    "author": "301+ Kim 301px",
    "source": "https://commons.wikimedia.org/wiki/File%3A301%2B_Kim_2015_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-77",
    "name": "272 Brunswick St, Fitzroy, Australia (Unsplash)",
    "file": "backgrounds/cc0-77.webp",
    "thumbnail": "backgrounds/thumbs/cc0-77.webp",
    "author": "Anthony Indraus aindraus",
    "source": "https://commons.wikimedia.org/wiki/File%3A272_Brunswick_St%2C_Fitzroy%2C_Australia_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-78",
    "name": "360 Rue Saint-Jacques, Montréal, Canada (Unsplash Yx7OJcooTvw)",
    "file": "backgrounds/cc0-78.webp",
    "thumbnail": "backgrounds/thumbs/cc0-78.webp",
    "author": "Crew crew",
    "source": "https://commons.wikimedia.org/wiki/File%3A360_Rue_Saint-Jacques%2C_Montr%C3%A9al%2C_Canada_(Unsplash_Yx7OJcooTvw).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-79",
    "name": "271 Divers (Unsplash)",
    "file": "backgrounds/cc0-79.webp",
    "thumbnail": "backgrounds/thumbs/cc0-79.webp",
    "author": "Adam Sherez mr_sherez",
    "source": "https://commons.wikimedia.org/wiki/File%3A271_Divers_(Unsplash).jpg",
    "color": "#183440"
  },
  {
    "id": "cc0-80",
    "name": "2 sleepy (Unsplash)",
    "file": "backgrounds/cc0-80.webp",
    "thumbnail": "backgrounds/thumbs/cc0-80.webp",
    "author": "Olya Kuzovkina o_l_l_a",
    "source": "https://commons.wikimedia.org/wiki/File%3A2_sleepy_(Unsplash).jpg",
    "color": "#183440"
  }
];
