export type Photo = {
  id: string;
  name: string;
  file: string;
  author: string;
  source: string;
  color: string;
};

export const photos: Photo[] = [
  {
    id: "forest",
    name: "Forest light",
    file: "backgrounds/forest.jpg",
    author: "SpessiG",
    source: "https://commons.wikimedia.org/wiki/File:Landscape_of_a_wild_forest.jpg",
    color: "#26352d",
  },
  {
    id: "mountains",
    name: "Mountain lake",
    file: "backgrounds/mountains.jpg",
    author: "Pikwizard",
    source: "https://commons.wikimedia.org/wiki/File:Mountains_Landscape.jpg",
    color: "#293c4a",
  },
  {
    id: "aurora",
    name: "Northern lights",
    file: "backgrounds/aurora.jpg",
    author: "Sebastian Kowalski",
    source: "https://commons.wikimedia.org/wiki/File:Northern_Lights_at_Lauklines_Norway.jpg",
    color: "#162c38",
  },
  {
    id: "melbourne",
    name: "City night",
    file: "backgrounds/melbourne.jpg",
    author: "Fafibelord",
    source: "https://commons.wikimedia.org/wiki/File:Melbourne_City_Skyline_2012.jpg",
    color: "#1c2633",
  },
  {
    id: "sunset",
    name: "Ocean sunset",
    file: "backgrounds/sunset.jpg",
    author: "Lisa Ann Yount",
    source: "https://commons.wikimedia.org/wiki/File:Sunset_over_ocean_(27717086074).jpg",
    color: "#563535",
  },
  {
    id: "perth",
    name: "Skyline lake",
    file: "backgrounds/perth.jpg",
    author: "Yourusernamewillbepublic2",
    source: "https://commons.wikimedia.org/wiki/File:Perth_City_Skyline_Across_Lake.jpg",
    color: "#274151",
  },
  {
    id: "lake-mountain",
    name: "Quiet mountain lake",
    file: "backgrounds/lake-mountain.jpg",
    author: "Bonnie Moreland",
    source: "https://commons.wikimedia.org/wiki/File:Lake_Mountain_Landscape.jpg",
    color: "#29394a",
  },
  {
    id: "colombo",
    name: "Colombo waterfront",
    file: "backgrounds/colombo.jpg",
    author: "Gihanud2001",
    source: "https://commons.wikimedia.org/wiki/File:Colombo_city_skyline_at_night.png",
    color: "#0b3a58",
  },
  {
    id: "kaohsiung",
    name: "Kaohsiung moonlight",
    file: "backgrounds/kaohsiung.jpg",
    author: "tingyaoh",
    source: "https://commons.wikimedia.org/wiki/File:Urban_skyline_of_Kaohsiung,_Taiwan_at_night.jpg",
    color: "#0b1f6a",
  },
  {
    id: "ocean-beach",
    name: "Pacific shore",
    file: "backgrounds/ocean-beach.jpg",
    author: "Daderot",
    source: "https://commons.wikimedia.org/wiki/File:Ocean_Beach_-_San_Francisco,_CA_-_01.jpg",
    color: "#6c8496",
  },
  {
    id: "coast",
    name: "Welsh coast",
    file: "backgrounds/coast.jpg",
    author: "diego_torres",
    source: "https://commons.wikimedia.org/wiki/File:Scenic_view_of_cloudy_landscape_with_sea_coast.jpg",
    color: "#447083",
  },
  {
    id: "alpine-lake",
    name: "Alpine reflection",
    file: "backgrounds/alpine-lake.jpg",
    author: "Pixel.la Free Stock Photos",
    source: "https://commons.wikimedia.org/wiki/File:Landscape-mountains-nature-lake_(24326735085).jpg",
    color: "#123f54",
  },
  {
    id: "waterfall",
    name: "Forest waterfall",
    file: "backgrounds/waterfall.jpg",
    author: "Martin Eklund",
    source: "https://commons.wikimedia.org/wiki/File:Waterfall_in_forest.jpg",
    color: "#2a3528",
  },
  {
    id: "merzouga",
    name: "Merzouga dunes",
    file: "backgrounds/merzouga.jpg",
    author: "Mustang Joe",
    source: "https://commons.wikimedia.org/wiki/File:The_Merzouga_dunes_of_Morocco.jpg",
    color: "#6a392d",
  },
  {
    id: "meadow",
    name: "Mountain meadow",
    file: "backgrounds/meadow.jpg",
    author: "Bonnie Moreland",
    source: "https://commons.wikimedia.org/wiki/File:Meadow_Landscape_Field.jpg",
    color: "#6b7142",
  },
  {
    id: "snow",
    name: "Winter range",
    file: "backgrounds/snow.jpg",
    author: "Patrick Hendry",
    source: "https://commons.wikimedia.org/wiki/File:Snow_mountain_background_photo_(Unsplash).jpg",
    color: "#2b3441",
  },
  {
    id: "cincinnati",
    name: "Cincinnati lights",
    file: "backgrounds/cincinnati.jpg",
    author: "EEJCC",
    source: "https://commons.wikimedia.org/wiki/File:Downtown_Cincinnati_skyline_at_night.jpg",
    color: "#171d2a",
  },
  {
    id: "city-lights",
    name: "City light trails",
    file: "backgrounds/city-lights.jpg",
    author: "Peng LIU",
    source: "https://commons.wikimedia.org/wiki/File:Long_exposure_of_urban_cityscape_at_night.jpg",
    color: "#12384a",
  },
  {
    id: "rice-terraces",
    name: "Sapa terraces",
    file: "backgrounds/rice-terraces.jpg",
    author: "Eerin25",
    source: "https://commons.wikimedia.org/wiki/File:Rice_terraces_in_Sapa,_Vietnam.jpg",
    color: "#576345",
  },
];
